// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...



class DefaultFirebaseOptions {

  
  static FirebaseOptions get currentPlatform {


    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKDy2vNdka-8NLvD2ZPQi7t7Yt9JQXj9A',
    appId: '1:336208504897:web:62aad0b11ab27998257ec0',
    messagingSenderId: '336208504897',
    projectId: 'baulkhos-2621',
    authDomain: 'baulkhos-2621.firebaseapp.com',
    storageBucket: 'baulkhos-2621.appspot.com',
    measurementId: 'G-50RCD5VTY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhQwJALKmwHkYriv8R4txbIKjsNs16GiQ',
    appId: '1:336208504897:android:dff80184e10dc196257ec0',
    messagingSenderId: '336208504897',
    projectId: 'baulkhos-2621',
    storageBucket: 'baulkhos-2621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEOljrImicwO3lbxBkdWcJoKE4qlU1rE',
    appId: '1:336208504897:ios:1e382743ced1754a257ec0',
    messagingSenderId: '336208504897',
    projectId: 'baulkhos-2621',
    storageBucket: 'baulkhos-2621.appspot.com',
    iosBundleId: 'com.example.baulkhos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEOljrImicwO3lbxBkdWcJoKE4qlU1rE',
    appId: '1:336208504897:ios:1e382743ced1754a257ec0',
    messagingSenderId: '336208504897',
    projectId: 'baulkhos-2621',
    storageBucket: 'baulkhos-2621.appspot.com',
    iosBundleId: 'com.example.baulkhos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKDy2vNdka-8NLvD2ZPQi7t7Yt9JQXj9A',
    appId: '1:336208504897:web:70875be5afe41f80257ec0',
    messagingSenderId: '336208504897',
    projectId: 'baulkhos-2621',
    authDomain: 'baulkhos-2621.firebaseapp.com',
    storageBucket: 'baulkhos-2621.appspot.com',
    measurementId: 'G-6LVG3N3K7R',
  );
}
